my_list = []
print("Before Append:",my_list)
my_list.append(10)
my_list.append(20)
my_list.append(30)
my_list.append(40)
print("After Append:",my_list)
my_list.insert(2,15)
print(my_list)
my_list.extend([50, 60,70])
print(my_list)
my_list.remove(70)
print(my_list)
print (my_list.index (30) )
print(my_list.sort())
print(my_list)
